import { useEffect, useRef, useState } from 'react';
import GrainField from './GrainField';
import { copyImage } from '../clipboard-image';
import { ArrowDownToLine, Clipboard, Copy, ImagePlus, LoaderCircle, Maximize2, RotateCcw, Trash2, X } from 'lucide-react';
import type { Asset, Draft, Run } from '../types';
export default function Gallery({ size, runs, assets, load, reuse, preview, retry, remove, hide, upscale }: { size:number; runs: Run[]; assets: Record<string, Asset>; load: (d: Draft) => void; reuse: (id: string) => void; preview: (a: Asset) => void; retry: (runId: string, jobId: string) => Promise<void>; remove: (id: string) => void; hide: (runId:string,jobId:string)=>void; upscale:(a:Asset)=>void }) {
 const grid=useRef<HTMLElement>(null),[width,setWidth]=useState(window.innerWidth-6);
 useEffect(()=>{const el=grid.current;if(!el)return;const observer=new ResizeObserver(([entry])=>setWidth(entry.contentRect.width));observer.observe(el);return()=>observer.disconnect();},[]);
 const [copyStatus,setCopyStatus]=useState(''),[menu,setMenu]=useState<{asset:Asset;x:number;y:number}|null>(null);
 const menuRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!copyStatus)return;const timeout=setTimeout(()=>setCopyStatus(''),4000);return()=>clearTimeout(timeout);},[copyStatus]);
 useEffect(()=>{if(!menu)return;menuRef.current?.querySelector('button')?.focus();const dismiss=(event:PointerEvent)=>{if(!menuRef.current?.contains(event.target as Node))setMenu(null);};const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenu(null);};window.addEventListener('pointerdown',dismiss);window.addEventListener('keydown',key);return()=>{window.removeEventListener('pointerdown',dismiss);window.removeEventListener('keydown',key);};},[menu]);
 const copy=(asset:Asset)=>{const promise=copyImage(asset.url);setMenu(null);setCopyStatus('Copying image…');void promise.then(()=>setCopyStatus('Image copied')).catch(e=>setCopyStatus(e.message||'Could not copy image.'));};
 const visible=runs.flatMap(run=>run.jobs.map(job=>({run,job,asset:job.assetId?assets[job.assetId]:null}))).filter(({job,asset})=>!job.hiddenAt&&!asset?.deletedAt);
 const target=width<720?Math.max(150,size*.65):size;
 const columns=Math.max(1,Math.floor((width+3)/(target+3))),tileWidth=(width-(columns-1)*3)/columns;
 const heights=Array.from({length:columns},()=>0);
 if (!visible.length) return <main ref={grid} className="library-empty"><GrainField/><h2>No images yet</h2><p>Enter a prompt and click Generate.</p></main>;
 return <main ref={grid} className="image-grid" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}} aria-label="Generated images">{visible.map(({run,job,asset}) => {
  const col=heights.indexOf(Math.min(...heights));
  const span=Math.ceil(asset?tileWidth*asset.height/asset.width:280)+3;
  const placement={gridColumn:col+1,gridRow:`${heights[col]+1} / span ${span}`};heights[col]+=span;
  if (!asset) return <article style={placement} className="pending-image" key={job.id} aria-label={`Image ${job.index + 1}: ${job.status}`}><button className="hide-job" aria-label="Hide generation" title="Hide this image. Generation may continue in the background." onClick={()=>hide(run.id,job.id)}><X size={16}/></button>{job.status === 'generating' || job.status === 'queued' ? <><LoaderCircle size={22} className={job.status === 'generating' ? 'spin' : ''}/><span>{job.status === 'generating' ? run.kind==='upscale'?'Upscaling':'Generating' : 'Queued'}</span></> : <><span>{job.status === 'interrupted' ? 'Interrupted' : run.kind==='upscale'?'Upscale failed':'Generation failed'}</span><p>{job.error}</p>{run.kind!=='upscale'&&<button onClick={() => void retry(run.id, job.id)}><RotateCcw size={14}/>Retry</button>}</>}</article>;
  return <article style={placement} className="image-tile" key={job.id} onContextMenu={event=>{event.preventDefault();setMenu({asset,x:Math.max(8,Math.min(event.clientX,window.innerWidth-192)),y:Math.max(8,Math.min(event.clientY,window.innerHeight-60))});}}><button className="image-open" onClick={() => preview(asset)} aria-label={`Preview image ${job.index + 1}`}><img src={asset.thumbnail} alt={run.draft.prompt.slice(0, 200)} width={asset.width} height={asset.height} loading="lazy"/></button><div className="image-actions"><button title="Copy image" aria-label="Copy image" onClick={()=>copy(asset)}><Clipboard size={16}/><span className="action-tooltip">Copy image</span></button><button title="Recreate" aria-label="Recreate" onClick={() => load(run.draft)}><Copy size={16}/><span className="action-tooltip">Recreate</span></button><button title="Upscale" aria-label="Upscale image" onClick={()=>upscale(asset)}><Maximize2 size={16}/><span className="action-tooltip">Upscale</span></button><button title="Use as reference" aria-label="Use image as reference" onClick={() => reuse(asset.id)}><ImagePlus size={16}/></button><a href={`${asset.url}?download=1`} title="Download original" aria-label="Download original image"><ArrowDownToLine size={16}/></a><button title="Delete image" aria-label="Delete image" onClick={() => remove(asset.id)}><Trash2 size={16}/><span className="action-tooltip">Delete</span></button></div><span className="image-dimensions">{asset.width} × {asset.height}{run.kind==='upscale'?' · SeedVR2':''}</span></article>;
 })}{menu&&<div ref={menuRef} className="node-context-menu" role="menu" aria-label="Image actions" style={{left:menu.x,top:menu.y}}><button role="menuitem" onClick={()=>copy(menu.asset)}>Copy image</button></div>}{copyStatus&&<div className="canvas-copy-status" role="status">{copyStatus}</div>}</main>;
}
