import { useEffect, useState } from 'react';
import type { Connection } from '../types';
import { api } from '../api';
export default function GenerationProvider({connection, changed}: {connection:Connection|null;changed:()=>Promise<void>}) {
  const [waiting,setWaiting]=useState(false),[error,setError]=useState('');
  const [workspaces,setWorkspaces]=useState<{id:string;name:string|null;credits:number}[]>([]);
  useEffect(()=>{if(!waiting)return;let stopped=false;const timer=setInterval(()=>{void api<Connection>('/api/connection').then(async c=>{if(stopped)return;if(c.connected){setWaiting(false);await changed();}else{const spaces=await api<typeof workspaces>('/api/higgsfield/workspaces');if(!stopped)setWorkspaces(spaces);}}).catch(()=>{});},3000);return()=>{stopped=true;clearInterval(timer);};},[waiting,changed]);
  async function select(provider:string){setError('');try{await api('/api/provider',{method:'PUT',body:JSON.stringify({provider})});await changed();}catch(e){setError((e as Error).message);}}
  return <><label className="quality-control"><span className="sr-only">Generation provider</span><select aria-label="Generation provider" value={connection?.provider||'openai'} onChange={e=>void select(e.target.value)}><option value="higgsfield">Higgsfield · credits</option><option value="codex">Codex · subscription</option><option value="openai">OpenAI API · pay per image</option></select></label>{connection?.provider==='higgsfield'&&<>{connection.connected?null:<button type="button" disabled={waiting} onClick={()=>{void api('/api/higgsfield/connect',{method:'POST'}).then(()=>setWaiting(true)).catch(e=>setError(e.message));}}>{waiting?'Signing in…':'Connect Higgsfield'}</button>}{workspaces.length>0&&!connection.connected&&<select aria-label="Higgsfield workspace" defaultValue="" onChange={e=>{void api('/api/higgsfield/workspace',{method:'PUT',body:JSON.stringify({id:e.target.value})}).then(async()=>{setWaiting(false);setWorkspaces([]);await changed();}).catch(e=>setError(e.message));}}><option value="" disabled>Choose workspace</option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name||'Personal'} · {Math.floor(w.credits)} credits</option>)}</select>}</>}{error&&<span role="alert">{error}</span>}</>;
}
