import {useEffect,useRef,useState} from 'react';
import {Plus,X,Maximize2,MoveDiagonal2,ArrowDownToLine,LoaderCircle} from 'lucide-react';
import type {Asset,StudioState} from '../types';
import {api} from '../api';
import {copyImage} from '../clipboard-image';
import {inputDimensions,outputDimensions} from '../resize';
import {arrangeNodes,childNode,legacyProject,makeProject,nodeSize,reconcileProjects,type CanvasNode,type UpscaleProject} from '../upscale-projects';
import ImageInspector from './ImageInspector';
const key='grain-upscale-projects-v1';
function readProjects():UpscaleProject[]{try{const p=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(p)?p.filter(p=>p&&typeof p.id==='string'&&Array.isArray(p.nodes)&&p.view):[];}catch{return [];}}
export default function UpscaleCanvas({asset,setAsset,state,refresh}:{asset:Asset|null;setAsset:(a:Asset|null)=>void;state:StudioState;refresh:()=>Promise<unknown>}){
 const [projects,setProjects]=useState<UpscaleProject[]>(()=>{const saved=readProjects();if(!localStorage.getItem('grain-canvas-migrated')){const legacy=legacyProject(state);if(legacy)saved.push(legacy);localStorage.setItem(key,JSON.stringify(saved));localStorage.setItem('grain-canvas-migrated','1');}return saved;}),[activeId,setActiveId]=useState(()=>localStorage.getItem('grain-upscale-active')||'');
 const [error,setError]=useState(''),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[compare,setCompare]=useState<string|null>(null),[archive,setArchive]=useState(false);
 const [keyOpen,setKeyOpen]=useState(false),[falKey,setFalKey]=useState(''),[savingKey,setSavingKey]=useState(false);
 const [contextMenu,setContextMenu]=useState<{asset:Asset;x:number;y:number}|null>(null),[copyStatus,setCopyStatus]=useState('');
 const menuRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!contextMenu)return;menuRef.current?.querySelector('button')?.focus();const dismiss=(e:PointerEvent)=>{if(!menuRef.current?.contains(e.target as Node))setContextMenu(null);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setContextMenu(null);};window.addEventListener('pointerdown',dismiss);window.addEventListener('keydown',escape);return()=>{window.removeEventListener('pointerdown',dismiss);window.removeEventListener('keydown',escape);};},[contextMenu]);
 useEffect(()=>{if(!copyStatus)return;const timer=setTimeout(()=>setCopyStatus(''),3500);return()=>clearTimeout(timer);},[copyStatus]);
 const canvas=useRef<HTMLDivElement>(null),file=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null),lock=useRef(false);
 const current=projects.find(p=>p.id===activeId&&!p.closed)||projects.find(p=>!p.closed);
 const selected=current?.nodes.find(n=>n.id===current.selectedId),selectedAsset=selected?.assetId?state.assets[selected.assetId]:undefined;
 const latest=useRef(projects);latest.current=projects;
 const persist=(next:UpscaleProject[])=>{try{localStorage.setItem(key,JSON.stringify(next));latest.current=next;setProjects(next);return true;}catch{setError('Project could not be saved. Free some local storage before continuing.');return false;}};
 const modify=(id:string,fn:(p:UpscaleProject)=>UpscaleProject)=>persist(latest.current.map(p=>p.id===id?fn(p):p));
 const patchNode=(projectId:string,id:string,patch:Partial<CanvasNode>)=>modify(projectId,p=>({...p,nodes:p.nodes.map(n=>n.id===id?{...n,...patch}:n)}));
 useEffect(()=>{localStorage.setItem('grain-upscale-active',activeId);},[activeId]);
 useEffect(()=>{void api<{configured:boolean}>('/api/fal/status').then(s=>setConfigured(s.configured)).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const next=reconcileProjects(latest.current,state);if(next!==latest.current)persist(next);},[state.runs]);
 const addProject=(a?:Asset)=>{const p=makeProject(`Upscale ${latest.current.length+1}`);if(a){const n={id:crypto.randomUUID(),assetId:a.id,x:0,y:0,percent:100,factor:2};p.nodes=[n];p.selectedId=n.id;}if(persist([...latest.current,p]))setActiveId(p.id);return p;};
 const consumed=useRef<string|null>(null);
 useEffect(()=>{if(asset&&consumed.current!==asset.id){consumed.current=asset.id;addProject(asset);setAsset(null);}},[asset?.id]);
 useEffect(()=>{if(compare)dialog.current?.showModal();else dialog.current?.close();},[compare]);
 const addImage=async(files:File[])=>{if(lock.current||!files.length)return;if(files.length!==1||!['image/png','image/jpeg','image/webp'].includes(files[0].type)||files[0].size>20*1024*1024){setError('Choose one PNG, JPG or WebP up to 20 MB.');return;}lock.current=true;setBusy(true);setError('');const projectId=current?.id;try{const body=new FormData();body.append('images',files[0]);const [a]=await api<Asset[]>('/api/assets',{method:'POST',body});await refresh();if(projectId){modify(projectId,p=>{const n={id:crypto.randomUUID(),assetId:a.id,x:p.nodes.length*380,y:0,percent:100,factor:2};return {...p,nodes:[...p.nodes,n],selectedId:n.id};});}else addProject(a);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 useEffect(()=>{const paste=(e:ClipboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea'))return;const files=Array.from(e.clipboardData?.files||[]);if(files.length){e.preventDefault();void addImage(files);}};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste);},[current?.id]);
 const submit=async()=>{if(!current||!selected||!selectedAsset||lock.current)return;let output;try{const input=inputDimensions(selectedAsset.width,selectedAsset.height,selected.percent);output=outputDimensions(input.width,input.height,selected.factor);}catch(e){setError((e as Error).message);return;}const node=childNode(selected,selectedAsset,current.nodes,state.assets);const projectId=current.id;const request={id:node.runId,assetId:selectedAsset.id,percent:selected.percent,factor:selected.factor};
 // Store the request snapshot before dispatch; a lost response can be recovered without a second charge.
 const pending={...node,request};if(!modify(projectId,p=>({...p,nodes:[...p.nodes,pending]})))return;lock.current=true;setBusy(true);setError('');try{await api('/api/upscales',{method:'POST',body:JSON.stringify(request)});await refresh();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}void output;};
 const retry=async(n:CanvasNode)=>{const request=(n as CanvasNode&{request?:unknown}).request;if(!request||lock.current)return;lock.current=true;setBusy(true);try{await api('/api/upscales',{method:'POST',body:JSON.stringify(request)});await refresh();setError('');}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 const [bounds,setBounds]=useState({width:900,height:600});useEffect(()=>{const el=canvas.current;if(!el)return;const o=new ResizeObserver(([e])=>setBounds({width:e.contentRect.width,height:e.contentRect.height}));o.observe(el);return()=>o.disconnect();},[]);
 const view=current?.view||{x:80,y:70,zoom:1};
 useEffect(()=>{const el=canvas.current;if(!el||!current)return;const id=current.id;const wheel=(e:WheelEvent)=>{e.preventDefault();const p=latest.current.find(p=>p.id===id);if(!p)return;const rect=el.getBoundingClientRect(),v=p.view;const z=Math.max(.03,Math.min(8,v.zoom*Math.exp(-e.deltaY*.003)));const x=e.clientX-rect.left,y=e.clientY-rect.top;modify(id,p=>({...p,view:{zoom:z,x:x-(x-v.x)*z/v.zoom,y:y-(y-v.y)*z/v.zoom}}));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[current?.id]);
 const gesture=useRef<{kind:'pan'|'move'|'resize';x:number;y:number;node?:CanvasNode;view:typeof view;projectId:string}|null>(null);
 const space=useRef(false);useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.code==='Space'&&!(e.target as HTMLElement).matches('input,textarea,button')){e.preventDefault();space.current=true;}};const up=()=>{space.current=false;};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',up);};},[]);
 const fit=()=>{if(!current?.nodes.length)return;const rects=current.nodes.map(n=>({...n,...nodeSize(n,n.assetId?state.assets[n.assetId]:undefined)}));const minX=Math.min(...rects.map(n=>n.x)),minY=Math.min(...rects.map(n=>n.y-40)),maxX=Math.max(...rects.map(n=>n.x+n.width)),maxY=Math.max(...rects.map(n=>n.y+n.height+40));const zoom=Math.max(.03,Math.min(2,(bounds.width-100)/(maxX-minX),(bounds.height-100)/(maxY-minY)));modify(current.id,p=>({...p,view:{zoom,x:(bounds.width-(maxX-minX)*zoom)/2-minX*zoom,y:(bounds.height-(maxY-minY)*zoom)/2-minY*zoom}}));};
 let dimensions='',invalid='';if(selectedAsset&&selected)try{const i=inputDimensions(selectedAsset.width,selectedAsset.height,selected.percent),o=outputDimensions(i.width,i.height,selected.factor);dimensions=`${i.width.toLocaleString()} × ${i.height.toLocaleString()} → ${o.width.toLocaleString()} × ${o.height.toLocaleString()}`;}catch(e){invalid=(e as Error).message;}
 const inspected=current?.nodes.find(n=>n.id===compare),image=inspected?.assetId?state.assets[inspected.assetId]:undefined,parent=current?.nodes.find(n=>n.id===inspected?.parentId),original=parent?.assetId?state.assets[parent.assetId]:undefined;
 return <main className="node-workspace">
 <div className="project-tabs" role="tablist" aria-label="Upscale projects">{projects.filter(p=>!p.closed).map(p=><div key={p.id} className="project-tab"><button role="tab" aria-selected={current?.id===p.id} onClick={()=>{setActiveId(p.id);setCompare(null);}}>{p.name}</button><button aria-label={`Close ${p.name}`} title="Close tab; project stays saved" onClick={()=>{modify(p.id,p=>({...p,closed:true}));setCompare(null);}}><X size={13}/></button></div>)}<button aria-label="New upscale project" onClick={()=>addProject()}><Plus size={17}/></button><button className="saved-projects" aria-expanded={archive} onClick={()=>setArchive(!archive)}>Saved projects</button></div>
 {archive&&<div className="project-archive">{projects.filter(p=>p.closed).map(p=><button key={p.id} onClick={()=>{modify(p.id,p=>({...p,closed:false}));setActiveId(p.id);setArchive(false);}}>{p.name} · {p.nodes.length} nodes</button>)}{!projects.some(p=>p.closed)&&<span>No closed projects</span>}</div>}
 <div className="node-layout"><div className="node-canvas" ref={canvas} tabIndex={0} aria-label="Upscale project canvas" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void addImage(Array.from(e.dataTransfer.files));}}
 onPointerDown={e=>{if(!current||e.button>1||(e.target as HTMLElement).closest('button'))return;const target=(e.target as HTMLElement).closest<HTMLElement>('[data-node]');const n=current.nodes.find(n=>n.id===target?.dataset.node);const kind=space.current||e.button===1||!n?'pan':'move';if(n&&kind==='move')modify(current.id,p=>({...p,selectedId:n.id}));gesture.current={kind,x:e.clientX,y:e.clientY,node:n,view:{...view},projectId:current.id};e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();}}
 onPointerMove={e=>{const g=gesture.current;if(!g)return;const dx=(e.clientX-g.x)/g.view.zoom,dy=(e.clientY-g.y)/g.view.zoom;if(g.kind==='pan')modify(g.projectId,p=>({...p,view:{...g.view,x:g.view.x+e.clientX-g.x,y:g.view.y+e.clientY-g.y}}));else if(g.node&&g.kind==='move')patchNode(g.projectId,g.node.id,{x:g.node.x+dx,y:g.node.y+dy});else if(g.node){const a=g.node.assetId?state.assets[g.node.assetId]:undefined;if(a){const w=a.width/4,h=a.height/4;patchNode(g.projectId,g.node.id,{percent:Math.max(10,Math.min(400,Math.round((g.node.percent+(dx*w+dy*h)/(w*w+h*h)*100)*10)/10))});}}}}
 onPointerUp={()=>{gesture.current=null;}} onPointerCancel={()=>{gesture.current=null;}}>
 <div className="node-world" style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.zoom})`}}>
 <svg className="node-edges" aria-hidden="true">{current?.nodes.map(n=>{const parent=current.nodes.find(p=>p.id===n.parentId);if(!parent)return null;const a=nodeSize(parent,parent.assetId?state.assets[parent.assetId]:undefined),b=nodeSize(n,n.assetId?state.assets[n.assetId]:undefined),x=parent.x+a.width,y=parent.y+a.height/2,x2=n.x,y2=n.y+b.height/2;return <path key={n.id} d={`M ${x} ${y} C ${x+90} ${y}, ${x2-90} ${y2}, ${x2} ${y2}`}/>;})}</svg>
 {current?.nodes.map(n=>{const a=n.assetId?state.assets[n.assetId]:undefined,s=nodeSize(n,a),run=state.runs.find(r=>r.id===n.runId),job=run?.jobs[0];return <div key={n.id} className={`canvas-node ${n.id===current.selectedId?'selected':''}`} data-node={n.id} onContextMenu={e=>{if(!a)return;e.preventDefault();e.stopPropagation();modify(current.id,p=>({...p,selectedId:n.id}));setContextMenu({asset:a,x:Math.max(8,Math.min(e.clientX,window.innerWidth-190)),y:Math.max(8,Math.min(e.clientY,window.innerHeight-60))});}} style={{left:n.x,top:n.y,width:s.width,height:s.height}} tabIndex={0} role="button" aria-label={a?`Select ${a.name}`:'Pending upscale'} onClick={()=>modify(current.id,p=>({...p,selectedId:n.id}))} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='Enter'){modify(current.id,p=>({...p,selectedId:n.id}));}const delta:Record<string,[number,number]>={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]};if(delta[e.key]){e.preventDefault();patchNode(current.id,n.id,{x:n.x+delta[e.key][0],y:n.y+delta[e.key][1]});}}} onDoubleClick={()=>a&&setCompare(n.id)}>
 <div className="node-name">{a?(n.parentId?'Upscaled':'Original'):'Upscale'}{a&&<span>{Math.round(a.width*n.percent/100)} × {Math.round(a.height*n.percent/100)}</span>}</div>
 {a?<img src={a.url} alt={a.name} draggable={false}/>:<div className="node-progress">{!job?<><span>Request not confirmed</span><button onClick={()=>void retry(n)}>Retry request</button></>:['queued','generating'].includes(job.status)?<><LoaderCircle className="spin"/><span>{job.status==='queued'?'Queued':'Upscaling…'}</span></>:<><span>{job.status}</span><small>{job.error}</small>{run?.falRequest&&<button onClick={()=>void api(`/api/upscales/${run.id}/retrieve`,{method:'POST'}).then(refresh).catch(e=>setError(e.message))}>Retrieve result</button>}</>}</div>}
 {n.parentId&&<i className="node-port input"/>}<i className="node-port output"/>
 {a&&n.id===current.selectedId&&<button className="node-resize" aria-label="Resize selected image" onPointerDown={e=>{e.stopPropagation();gesture.current={kind:'resize',x:e.clientX,y:e.clientY,node:{...n},view:{...view},projectId:current.id};canvas.current?.setPointerCapture(e.pointerId);}} onKeyDown={e=>{const delta=e.key==='ArrowRight'||e.key==='ArrowUp'?1:e.key==='ArrowLeft'||e.key==='ArrowDown'?-1:0;if(delta){e.preventDefault();patchNode(current.id,n.id,{percent:Math.max(10,Math.min(400,n.percent+delta))});}}}><MoveDiagonal2 size={15}/></button>}
 </div>;})}</div>
 {!current?.nodes.length&&<div className="node-empty"><button onClick={()=>file.current?.click()}><Plus size={20}/>Add image</button><span>Drop or paste an image</span></div>}
 <div className="canvas-navigation"><button onClick={fit}><Maximize2 size={14}/>Fit all</button><button onClick={()=>current&&modify(current.id,p=>({...p,nodes:arrangeNodes(p.nodes,state.assets)}))}>Arrange</button><span>{Math.round(view.zoom*100)}%</span></div>
 </div><aside className="node-settings"><input ref={file} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={e=>{void addImage(Array.from(e.target.files||[]));e.target.value='';}}/>
 <button className="upload-source" disabled={busy} onClick={()=>file.current?.click()}><Plus size={15}/>Add image</button>
 {current&&<label className="project-name">Project<input aria-label="Project name" value={current.name} maxLength={80} onChange={e=>modify(current.id,p=>({...p,name:e.target.value}))}/></label>}
 {selectedAsset&&selected&&current?<><h2>{selected.parentId?'Upscaled image':'Original image'}</h2><label>Input size <div className="percent-input"><input aria-label="Node input percent" type="number" min={10} max={400} step={.1} value={selected.percent} onChange={e=>patchNode(current.id,selected.id,{percent:Number(e.target.value)})}/>%</div></label><input aria-label="Resize node input" type="range" min={10} max={400} step={.1} value={selected.percent} onChange={e=>patchNode(current.id,selected.id,{percent:Number(e.target.value)})}/><div className="resolution-presets">{[1024,2048,4096].map(size=>{const percent=size/Math.max(selectedAsset.width,selectedAsset.height)*100;return <button disabled={percent<10||percent>400} key={size} onClick={()=>patchNode(current.id,selected.id,{percent})}>{size/1024}K</button>;})}<button onClick={()=>patchNode(current.id,selected.id,{percent:100})}>Original</button></div><label>Upscale by</label><div className="factor-options">{[2,4].map(f=><button key={f} aria-pressed={selected.factor===f} onClick={()=>patchNode(current.id,selected.id,{factor:f})}>{f}×</button>)}</div><p className="node-dimensions">{dimensions}</p><button className="generate-button" disabled={busy||!configured||!!invalid} onClick={()=>void submit()}>Upscale → new node</button><button className="upload-source" onClick={()=>setCompare(selected.id)}>{selected.parentId?'Compare with parent':'Inspect image'}</button><a className="download-result" href={`${selectedAsset.url}?download=1`}><ArrowDownToLine size={15}/>Download</a></>:<p>Select an image node to resize or upscale it.</p>}
 {(error||invalid)&&<p role="alert" className="panel-error">{error||invalid}</p>}{!configured&&<button className="key-open" onClick={()=>setKeyOpen(true)}>Add fal API key</button>}
 </aside></div>
 {contextMenu&&<div ref={menuRef} className="node-context-menu" role="menu" aria-label="Image actions" style={{left:contextMenu.x,top:contextMenu.y}}><button role="menuitem" onClick={()=>{const promise=copyImage(contextMenu.asset.url);setContextMenu(null);setCopyStatus('Copying image…');void promise.then(()=>setCopyStatus('Image copied')).catch(e=>{setCopyStatus('');setError(e.message||'Could not copy image.');});}}>Copy image</button></div>}
 {copyStatus&&<div className="canvas-copy-status" role="status">{copyStatus}</div>}
 {keyOpen&&<div className="key-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setKeyOpen(false);}}><form className="key-dialog" aria-label="Connect fal" onSubmit={async e=>{e.preventDefault();setSavingKey(true);try{await api('/api/fal/key',{method:'PUT',body:JSON.stringify({key:falKey})});setConfigured(true);setFalKey('');setKeyOpen(false);setError('');}catch(e){setError((e as Error).message);}finally{setSavingKey(false);}}}><header><strong>fal API key</strong><button type="button" aria-label="Close" onClick={()=>setKeyOpen(false)}><X size={16}/></button></header><input autoFocus type="password" value={falKey} onChange={e=>setFalKey(e.target.value)} placeholder="Paste key" autoComplete="off" spellCheck={false}/><button className="generate-button" disabled={savingKey||falKey.trim().length<10}>{savingKey?'Saving':'Save key'}</button></form></div>}
 <dialog className="preview-dialog" ref={dialog} aria-label="Inspect canvas image" onCancel={()=>setCompare(null)}>{image&&<><div className="preview-heading"><h2>{original?'Compare with parent':'Image'}</h2><button aria-label="Close inspector" onClick={()=>setCompare(null)}><X/></button></div><ImageInspector key={image.id} image={image} original={original}/></>}</dialog>
 </main>;
}
